### ISSUE TITLE
Follow sync status

### ISSUE THREAD

**Issue by khaninejad** [zarbchain/zarb-go#190]
### Describe the problem you'd like to have solved

This is impossible to follow the Zarb validator sync status. we need progress or some kind of data that shows us the progress of the operation. The output isn't clear to understand the sync status when we started a new validator node.

### Describe the ideal solution

Implement a sync progress or remaining block count.

**Comment by b00f** [comment]
@khaninejad in the GUI application we have implemented a progress bar that shows how much of the blocks are synced so far.
![Screenshot from 2022-08-26 20-12-36](https://user-images.githubusercontent.com/8073510/186900908-c82c3cb1-66dc-47d3-8e72-00a7075d042e.png)
