### ISSUE TITLE
WWW: Refactor gRPC API Messages

### ISSUE THREAD

**Issue by d4rk5h0t** [zarbchain/zarb-go#209]
### Describe the problem you'd like to have solved

current implementation of gRPC server consist of 2 API message types which makes interaction with the API a bit harder

### Describe the ideal solution

make all the gRPC APIs return and receive same structures 
It may be better to define distinct object structures to be return from APIs but It might make querying server harder but since RPC server isn't query service I think its better to take care of queries with explorer services or wrap it on GraphQL service and have uniform APIs on RPC side
## Alternatives and current work-arounds

refactor APIs to return same structures types as example of this issue in [PR 204](https://github.com/zarbchain/zarb-go/pull/204/files?file-filters%5B%5D=.go&file-filters%5B%5D=.json&file-filters%5B%5D=.proto#diff-3be930d36fe301f565030d3d1faf0ce8d50dc958a4d83cd5ed45a8e4bfa4b406R17-R37) there are 2 different implementations of client which are fairly similar

**Comment by Ali-Meh** [comment]
I agree And I can get it done but which way we gonna take
we need all APIs feel same either way I can refactor all to verbose thing or defined structs

**Comment by b00f** [comment]
Yes. You are right. Right now we have two different approaches for gRPC which is a bit confusing. 
For sake of simplicity we can think about different output level. 
For example, 'getBlock' method: 
- with verbosity 0 just returns block data. 
- with verbosity 1 returns block information 
- with verbosity 2 returns block and transaction information 

This is almost same as getBlock RPC method in [Bitcoin](https://developer.bitcoin.org/reference/rpc/getblock.html)

**Comment by Ali-Meh** [comment]
> For example, 'getBlock' method:
> 
>     * with verbosity 0 just returns block data.
> 
>     * with verbosity 1 returns block information
> 
>     * with verbosity 2 returns block and transaction information

@b00f 
there is no doubt we might need this kind of verbosity levels in gRPC we can achieve this by not filling sub structs or messages but right now there is no struct to begin with 

we first need to decide if we want to have solid predefined object messages or dynamic base64 encoded json messages

**Comment by b00f** [comment]
@Ali-Meh @d4rk5h0t  I think we can close this issue now.
