### ISSUE TITLE
'make all' command failed  Macbookpro M1 chip  

### ISSUE THREAD

**Issue by nagarajmanjunath** [zarbchain/zarb-go#218]
### Description

> latest code not able build in M1 one chip.

## How To Reproduce
> using Macbook pro M1 chip
> git clone `https://github.com/zarbchain/zarb-go.git`
> make all 

## What Happened
> ` "_mclBn_setETHserialization", referenced from:
      __cgo_0f415fd17c22_Cfunc_mclBn_setETHserialization in _x004.o
     (maybe you meant: __cgo_0f415fd17c22_Cfunc_mclBn_setETHserialization)
  "_mclBn_setMapToMode", referenced from:
      __cgo_0f415fd17c22_Cfunc_mclBn_setMapToMode in _x004.o
     (maybe you meant: __cgo_0f415fd17c22_Cfunc_mclBn_setMapToMode)
  "_mclBn_verifyOrderG1", referenced from:
      __cgo_0f415fd17c22_Cfunc_mclBn_verifyOrderG1 in _x004.o
     (maybe you meant: __cgo_0f415fd17c22_Cfunc_mclBn_verifyOrderG1)
  "_mclBn_verifyOrderG2", referenced from:
      __cgo_0f415fd17c22_Cfunc_mclBn_verifyOrderG2 in _x004.o
     (maybe you meant: __cgo_0f415fd17c22_Cfunc_mclBn_verifyOrderG2)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [install] Error 2`

## Expected Behavior
>`make all` should build the binary

### Environment

> chip: Apple M1
> os: MacOs Big sure V11.3.1

**Comment by d4rk5h0t** [comment]
@nagarajmanjunath 

hi there thanks for bringing this up unfortunately I don't have access to M1 to check this but it seems issues resides in `bls` library we using and has kind of linking issue

could you try without `CGO_LDFLAGS` and try to install with out linker/loader flags and run only `go build ./cmd/zarb`?

if issue still persist could you try [pre-built bls](https://github.com/herumi/bls-go-binary) archive and refrence it in your `CGO_LDFLAGS` and try again?

**Comment by b00f** [comment]
You can build like this: `go build ./cmd/zarb'
