### ISSUE TITLE
Not able to create bond transaction on network

### ISSUE THREAD

**Issue by nagarajmanjunath** [zarbchain/zarb-go#219]
### Description

> Not able to stake or bond validator using cmd `zarb tx bond`

## How To Reproduce
> Use below command 
    `tx bond --bonder {address of bonder} --pub {pub key of validator} --stake 5000000 --fee 00002000 --stamp {latestblockhash} --keyfile ~/zarb/keystore —e http://mainnet:port`
## What Happened
> When I run above command I get `error: Error: incorrect usage`

## Expected Behavior
> Send the bonding transaction

## Extra
> zarb tx bond command issue 

### Environment

> Please provide the following:

- **Os: Big sure 11.3.1**
- ZarbVersion: latest

**Comment by b00f** [comment]
Please replace "—e" with "-"
