### ISSUE TITLE
Coudn't get balance for some address

### ISSUE THREAD

**Issue by khaninejad** [zarbchain/zarb-go#224]
### Description

I am trying to get the addresses balance using the API /account/address/zrb17mka0cw484es5whq638xkm89msgzczmrwy64dy but this API returns:

> www/capnp/zarb.capnp:ZarbServer.getAccount: rpc exception: account not found

## How To Reproduce
http://172.104.186.100:8081/account/address/zrb17mka0cw484es5whq638xkm89msgzczmrwy64dy

## What Happened
> www/capnp/zarb.capnp:ZarbServer.getAccount: rpc exception: account not found

## Expected Behavior
```
{
  "Address": "zrb17mka0cw484es5whq638xkm89msgzczmrwy64dy",
  "Number": 0,
  "Sequence": 0,
  "Balance": 000000000000
}
or at least a catchable JSON error. 
```

**Comment by d4rk5h0t** [comment]
@khaninejad 
I highly recommend using gRPC service and protofile to have better and smoother API calls which has REST interface available on port `8080` and gRPC service available on port `9090`

which returns errors and data in better format even though highly unstable as of PR #223 still is better option for same [porpuse](http://172.104.186.100:8080/api/account/address/%23%20zarb-sdk%20Typescript%20nodejs%20sdk%20for%20intracting%20with%20zarb%20blockchain?verbosity=1)

let me know if you gonna switch or how much we need to fix this issue

**Comment by b00f** [comment]
@khaninejad If an account has not received any transactions yet, it won't be created.
In this case this address probably is the validator address. Validators and accounts are two different objects. A validator might have an account or not and vice versa.

With your permission I closed this issue. Thanks for reporting it.
