### ISSUE TITLE
Separating Daemon and CLI 

### ISSUE THREAD

**Issue by b00f** [zarbchain/zarb-go#227]
## Describe the problem you'd like to have solved

Right now there is one command for starting the blockchain and other stuff like generating key and signing the messages.
It's better to have two different commands for running blockchain as daemon and CLI functionalities. 

### Describe the ideal solution

Two different executable:
- `zarbd`: a daemon for running blockchain
- `zarb-cli`: a tool can run command like generating keys, etc...

**Comment by b00f** [comment]
@yenkhoon @d4rk5h0t @mhatvan @ali-mahdavi99 
Any volunteers working on this issue?

**Comment by yenkhoon** [comment]
I will work on this, can assign to me!

**Comment by yenkhoon** [comment]
@b00f can assign the issue to me? i cant assign to myself.

**Comment by b00f** [comment]
Done.
