### ISSUE TITLE
Usage of deprecated package ripemd160

### ISSUE THREAD

**Issue by mcmxcdev** [zarbchain/zarb-go#236]
## Description

`go-staticcheck` for `golang.org/x/crypto/ripemd160` import in `/crypto/hash/hash.go` reports the following:

`SA1019: package golang.org/x/crypto/ripemd160 is deprecated: RIPEMD-160 is a legacy hash and should not be used for new applications. Also, this package does not and will not provide an optimized implementation. Instead, use a modern hash like SHA-256 (from crypto/sha256). (staticcheck)`

### How To Reproduce

- Open the project in e.g. Visual Studio Code with Go Extension enabled
- Expect warning message to pop up in Problems tab of VSCode

### Expected Behavior

No issues are showing up.

### Environment

- **Operation System:** Manjaro Linux
- **Zarb Version:** 0.9.0-beta+dfc3a19a
- **Go Version:** 1.17.5

**Comment by b00f** [comment]
@mhatvan 

To generate address from the public key, first we apply Hash160 (RIPEMD-160) on Hash256 (Blake2b) on publick key: https://github.com/zarbchain/zarb-go/blob/cc6780badceee8a3b71852e5140adcd57a3dcea1/crypto/bls/public_key.go#L130-L135

We also have discussed about it [here](https://zarb.network/guide/learn-cryptography.html#address-conversion)

About [second-preimage attack](https://en.wikipedia.org/wiki/Preimage_attack) for RIPEMD-160 hash function, I found [this](https://en.wikipedia.org/wiki/Hash_function_security_summary#Preimage_resistance_2)

Bitcoin almost uses the same approach to generate 20 bytes address: [here](https://github.com/btcsuite/btcutil/blob/master/address.go#L338-L340) and [here](https://github.com/btcsuite/btcd/blob/master/btcutil/hash160.go)

So in my point of view, using RIPEMD-160 should be safe. I am not a cryptographer, but I can trust Bitcoin!

**Comment by mhatvan** [comment]
Thank you for the detailed explanation

It sounds like the implementation is fine then, we will just always have the deprecation notice then from `staticcheck`. It might make sense to silence it.

**Comment by jwmdev** [comment]
@b00f is this still an issue or already resolved? If already resolved, can we close it?

**Comment by b00f** [comment]
@jwmdev Yes, We can close it now.

**Comment by b00f** [comment]
@mcmxcdev This warning is disable in `Makefile` . Look here: https://github.com/zarbchain/zarb-go/blob/403f1c569ca1c220062f4e10e7d9e9c0f43b8e15/Makefile#L73
