### ISSUE TITLE
Upgrading libp2p package

### ISSUE THREAD

**Issue by b00f** [zarbchain/zarb-go#238]
Right now we are using libp2p version 0.12.0, the latest version at this time is 0.17.0. Update the network pcakge to use the latest version of libp2p.

**Comment by b00f** [comment]
@mhatvan what do you think about this issue? It is easy at the same time you can work with libp2p stuff. It's cool.

**Comment by mhatvan** [comment]
Hey Mostafa, it sounds interesting to me!

It might take me a couple of days to start with it, but I want to do it.
