### ISSUE TITLE
Testnext

### ISSUE THREAD

**Issue by irwanambak** [zarbchain/zarb-go#274]
WARN[0148] firewall: unable to open a stream bundle      _sync="{☍ 6 ⛃ 4601 ⇈ 42519 ↑ 839}" err="invalid message: invalid message: stream reset"

What's this? My machine or server end?

## Description

> Provide a clear and concise description of the issue, including what you expected to happen.

### How To Reproduce

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.

### What Happened

> What actually happened including any error log or so

### Expected Behavior

> What were you expecting

### Extra

> any extra information you think is relevant to issue

### Environment

- **Operation System: **
- **Zarb Version: **
- **Go Version**

**Comment by b00f** [comment]
@irwanambak thanks. I will look at it soon. Kt looks weird

**Comment by themantre** [comment]
A stream reset is an abrupt interruption of the stream by libp2p. It is discussed [here](https://discuss.libp2p.io/t/what-causes-a-stream-reset/253)
