### ISSUE TITLE
Missing `Height` parameter in gRPC GetBlock 

### ISSUE THREAD

**Issue by nagarajmanjunath** [zarbchain/zarb-go#286]
## Description

> `gRPC GetBlock` RPC call response, does not contains height parameter.

### How To Reproduce

> `grpc` `GetBlock` RPC call.

### What Happened

> missing `Height` parameter in in RPC call `GetBlock`

### Environment

- **Operation System: `Mac Osx` **
- **Zarb Version: `Zarb version: 0.9.0-beta+3bdb9865`**
- **Go Version : go version go1.18 darwin/amd64**

**Comment by b00f** [comment]
It's fixed. Look here: https://github.com/zarbchain/zarb-go/blob/403f1c569ca1c220062f4e10e7d9e9c0f43b8e15/www/grpc/proto/zarb.proto#L66
