### ISSUE TITLE
Moving vote and proposal into types

### ISSUE THREAD

**Issue by themantre** [zarbchain/zarb-go#313]
`vote` and `proposal` packages under `consensus` can move into `types` package. 
They are kind of type package and they are using by other packages (like `sync`). 

Related to #310

**Comment by themantre** [comment]
@yenkhoon what do you think?

**Comment by yenkhoon** [comment]
i will work on this

**Comment by yenkhoon** [comment]
@themantre the vote and proposal packages is currently under consensus, do i move both of them out into types package?

**Comment by themantre** [comment]
@yenkhoon yes. `vote` and `proposal` both are using inside `sync` package. So they are common between `consensus` and `sync`. Better we move them into `types`

**Comment by yenkhoon** [comment]
can close this issue.
