### ISSUE TITLE
Windows releaser has failed

### ISSUE THREAD

**Issue by b00f** [zarbchain/zarb-go#350]
## Description

Windows releaser for GUI app has failed. The log is available [here](https://github.com/zarbchain/zarb-go/runs/7977200376?check_suite_focus=true)

### How To Reproduce

Running the windows release action for GUI will produce this issue.

### What Happened

Can't find a DLL:
```
cp: cannot stat 'libffi-7.dll': No such file or directory
```

### Expected Behavior

Should be able to copy the missed DLL.

### Environment

- **Operation System: ** Windows
- **Zarb Version: ** Latest
- **Go Version** 1.18

**Comment by jwmdev** [comment]
> ## Description
> 
> Windows releaser for GUI app has failed. The log is available [here](https://github.com/zarbchain/zarb-go/runs/7977200376?check_suite_focus=true)
> ### How To Reproduce
> 
> Running the windows release action for GUI will produce this issue.
> ### What Happened
> 
> Can't find a DLL:
> 
> ```
> cp: cannot stat 'libffi-7.dll': No such file or directory
> ```
> 
> ### Expected Behavior
> 
> Should be able to copy the missed DLL.
> ### Environment
> 
>     * **Operation System: ** Windows
> 
>     * **Zarb Version: ** Latest
> 
>     * **Go Version** 1.18

The github workfolow  - window build test passed. In the workflow, the requirement is go v1.19 and not v1.18. Can you try to upgrade your go and build again?

**Comment by b00f** [comment]
@jwmdev Let me try it. I have a windows in virtual machine. I can test it there.
