### ISSUE TITLE
Version api

### ISSUE THREAD

**Issue by jwmdev** [zarbchain/zarb-go#375]
## Describe the problem you'd like to have solved
The api is not versioned

### Describe the ideal solution

The api should be versioned e.g v1, v2 etc... and the corresponding end points houd be update eg `/api/block/hash/{hash}` should be replaced by `/api/v1/block/hash/{hash}`

**Comment by b00f** [comment]
It is done for REST APIs in is fixed in #376 . 
How about gRPC versioning? @ali-mahdavi99 do you have any solution?
